apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  gateway.yml: |-
    {{- with .Values.gateway_file_content }}
      {{- toYaml . | nindent 4 }}
    {{- end  }}
---
{{- if .Values.agent_file_content }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-agent-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  agent.yml: |-
    {{- with .Values.agent_file_content }}
      {{- toYaml . | nindent 4 }}
    {{- end  }}
---
{{- end }}