apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http-agent
      port: {{ .Values.service.httpAgentPort }}
      protocol: TCP
    - name: http
      port: {{ .Values.service.httpPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.httpNodeport }}
      {{- end }}
      protocol: TCP
    - name: api
      port: {{ .Values.service.apiPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.apiNodeport }}
      {{- end }}
      protocol: TCP
      