apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "gateway.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOGGING_ES_ENDPOINT
              value: {{ .Values.env.loggingEsEndpoint }}
            - name: LOGGING_ES_USER
              value: {{ .Values.env.loggingEsUser }}
            - name: LOGGING_ES_PASS
              value: {{ .Values.env.loggingEsPass }}
            - name: PROD_ES_ENDPOINT
              value: {{ .Values.env.prodEsEndpoint }}
            - name: PROD_ES_USER
              value: {{ .Values.env.prodEsUser }}
            - name: PROD_ES_PASS
              value: {{ .Values.env.prodEsPass }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: api
              containerPort: {{ .Values.service.apiPort }}
              protocol: TCP
          volumeMounts:
            - name: gateway-data
              mountPath: /data
            - name: gateway-config
              mountPath: /gateway.yml
              subPath: gateway.yml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: gateway-data
          emptyDir: {}
        - name: gateway-config
          configMap:
            name: {{ include "gateway.fullname" . }}-config
            defaultMode: 420
            items: 
              - key: gateway.yml
                path: gateway.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: gateway-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.dataVolumeStorage }}
