apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-ca
spec:
  commonName: certificate-ca
  duration: 87600h0m0s
  isCA: true
  issuerRef:
    kind: Issuer
    name: issuer-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 2160h0m0s
  secretName: ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "infini-easysearch.fullname" . }}-ca
spec:
  dnsNames:
  - infini.cloud
  duration: 87600h0m0s
  issuerRef:
    kind: Issuer
    name: {{ include "infini-easysearch.fullname" . }}-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  renewBefore: 2160h0m0s
  secretName: {{ include "infini-easysearch.fullname" . }}-ca-secret
  subject:
    organizations:
    - infinilabs
