apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-ca
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "infini-easysearch.fullname" . }}-issuer
spec:
  ca:
    secretName: ca-secret