apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "easysearch.fullname" . }}-instance-certificate
spec:
  dnsNames:
  - infinilabs.com
  duration: 87600h0m0s
  issuerRef:
    kind: Issuer
    name: {{ include "easysearch.fullname" . }}-instance-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  renewBefore: 2160h0m0s
  secretName: {{ include "easysearch.fullname" . }}-instance-secret
  subject:
    organizations:
    - infinilabs
