apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easysearch.fullname" . }}-config-toml
  labels:
    {{- include "easysearch.labels" . | nindent 4 }}
data:
  confd.toml: |
    [template]
    src = "confd.tmpl"
    dest = "/etc/confd/easysearch.yml"
    uid = 602
    gid = 602
    mode = "0644"
    keys = ["/",]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easysearch.fullname" . }}-config-tmpl
  labels:
    {{- include "easysearch.labels" . | nindent 4 }}
data:
  confd.tmpl: |-
    cluster.name: {\{getenv "CLUSTER_NAME"}\}
    node.name: {\{getenv "NODE_NAME"}\}
    #node.attr.rack: r1
    #path.data: /path/to/data
    #path.logs: /path/to/logs
    #bootstrap.memory_lock: true
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    node.roles: [{\{getenv "NODE_ROLES"}\}]
    discovery.seed_hosts: [{\{getenv "DISCOVERY_SEED_HOSTS"}\}]
    cluster.initial_master_nodes: [{\{getenv "MASTER_HOSTS"}\}]
    #gateway.recover_after_nodes: 3
    #action.destructive_requires_name: true
    #cluster.routing.allocation.disk.threshold_enabled: false
    #node.max_local_storage_nodes: 3
    #bootstrap.system_call_filter: false
    #elasticsearch.api_compatibility: true
    
    security.enabled: false
    security.audit.type: noop
    security.ssl.transport.cert_file: instance.crt
    security.ssl.transport.key_file: instance.key
    security.ssl.transport.ca_file: ca.crt
    security.ssl.transport.skip_domain_verify: true
    security.ssl.http.enabled: false
    security.ssl.http.cert_file: instance.crt
    security.ssl.http.key_file: instance.key
    security.ssl.http.ca_file: ca.crt
    security.ssl.http.enabled_ciphers:
      - "TLS_AES_128_GCM_SHA256"
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
      - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
      - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    security.ssl.http.enabled_protocols:
      - "TLSv1.2"
      - "TLSv1.3"
    security.allow_default_init_securityindex: true
    
    security.nodes_dn:
      - 'O=infinilabs'
    
    security.restapi.roles_enabled: [ "superuser", "security_rest_api_access" ]
    
    security.system_indices.enabled: true
    security.ssl.http.clientauth_mode: OPTIONAL
    security.system_indices.indices: [".infini-*"]
    
    #for admin dn
    ## specify admin certs to operate against system indices, basic_auth is not required
    ##  curl -k  --cert config/admin.crt --key config/admin.key   -XDELETE 'https://localhost:9200/.infini-*/'
    security.authcz.admin_dn:
      - 'O=infinilabs'
  jvm.options: |-
    ## JVM configuration

    ################################################################
    ## IMPORTANT: JVM heap size
    ################################################################
    ##
    ## You should always set the min and max JVM heap
    ## size to the same value. For example, to set
    ## the heap to 4 GB, set:
    ##
    ## -Xms4g
    ## -Xmx4g
    ##
    ## See https://infinilabs.com/docs/latest/easysearch/getting-started/install/#JVM
    ## for more information
    ##
    ################################################################

    # Xms represents the initial size of total heap space
    # Xmx represents the maximum size of total heap space

    -Xms1g
    -Xmx1g

    ################################################################
    ## Expert settings
    ################################################################
    ##
    ## All settings below this section are considered
    ## expert settings. Don't tamper with them unless
    ## you understand what you are doing
    ##
    ################################################################

    ## GC configuration
    8-10:-XX:+UseConcMarkSweepGC
    8-10:-XX:CMSInitiatingOccupancyFraction=75
    8-10:-XX:+UseCMSInitiatingOccupancyOnly

    ## G1GC Configuration
    # NOTE: G1 GC is only supported on JDK version 10 or later
    # to use G1GC, uncomment the next two lines and update the version on the
    # following three lines to your version of the JDK
    # 10-13:-XX:-UseConcMarkSweepGC
    # 10-13:-XX:-UseCMSInitiatingOccupancyOnly
    11-:-XX:+UseG1GC
    11-:-XX:G1ReservePercent=25
    11-:-XX:InitiatingHeapOccupancyPercent=30

    ## JVM temporary directory
    -Djava.io.tmpdir=${ES_TMPDIR}

    ## JSM configuration
    17-:-Djava.security.manager=allow

    ## Locale configuration
    9-20:-Djava.locale.providers=SPI,COMPAT
    21-:-Djava.locale.providers=SPI,CLDR

    ## heap dumps

    # generate a heap dump when an allocation from the Java heap fails
    # heap dumps are created in the working directory of the JVM
    -XX:+HeapDumpOnOutOfMemoryError

    # specify an alternative path for heap dumps; ensure the directory exists and
    # has sufficient space
    -XX:HeapDumpPath=data

    # specify an alternative path for JVM fatal error logs
    -XX:ErrorFile=logs/hs_err_pid%p.log

    ## JDK 8 GC logging
    8:-XX:+PrintGCDetails
    8:-XX:+PrintGCDateStamps
    8:-XX:+PrintTenuringDistribution
    8:-XX:+PrintGCApplicationStoppedTime
    8:-Xloggc:logs/gc.log
    8:-XX:+UseGCLogFileRotation
    8:-XX:NumberOfGCLogFiles=32
    8:-XX:GCLogFileSize=64m

    # JDK 9+ GC logging
    9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
  log4j2.options: |-
    status=error
    appender.console.type=Console
    appender.console.name=console
    appender.console.layout.type=PatternLayout
    appender.console.layout.pattern=[%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
    ######## Server JSON ############################
    appender.rolling.type=RollingFile
    appender.rolling.name=rolling
    appender.rolling.fileName=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_server.json
    appender.rolling.layout.type=ESJsonLayout
    appender.rolling.layout.type_name=server
    appender.rolling.filePattern=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}-%d{yyyy-MM-dd}-%i.json.gz
    appender.rolling.policies.type=Policies
    appender.rolling.policies.time.type=TimeBasedTriggeringPolicy
    appender.rolling.policies.time.interval=1
    appender.rolling.policies.time.modulate=true
    appender.rolling.policies.size.type=SizeBasedTriggeringPolicy
    appender.rolling.policies.size.size=128MB
    appender.rolling.strategy.type=DefaultRolloverStrategy
    appender.rolling.strategy.fileIndex=nomax
    appender.rolling.strategy.action.type=Delete
    appender.rolling.strategy.action.basepath=${sys:es.logs.base_path}
    appender.rolling.strategy.action.condition.type=IfFileName
    appender.rolling.strategy.action.condition.glob=${sys:es.logs.cluster_name}-*
    appender.rolling.strategy.action.condition.nested_condition.type=IfAccumulatedFileSize
    appender.rolling.strategy.action.condition.nested_condition.exceeds=2GB
    ################################################
    ######## Server -  old style pattern ###########
    appender.rolling_old.type=RollingFile
    appender.rolling_old.name=rolling_old
    appender.rolling_old.fileName=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}.log
    appender.rolling_old.layout.type=PatternLayout
    appender.rolling_old.layout.pattern=[%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
    appender.rolling_old.filePattern=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}-%d{yyyy-MM-dd}-%i.log.gz
    appender.rolling_old.policies.type=Policies
    appender.rolling_old.policies.time.type=TimeBasedTriggeringPolicy
    appender.rolling_old.policies.time.interval=1
    appender.rolling_old.policies.time.modulate=true
    appender.rolling_old.policies.size.type=SizeBasedTriggeringPolicy
    appender.rolling_old.policies.size.size=128MB
    appender.rolling_old.strategy.type=DefaultRolloverStrategy
    appender.rolling_old.strategy.fileIndex=nomax
    appender.rolling_old.strategy.action.type=Delete
    appender.rolling_old.strategy.action.basepath=${sys:es.logs.base_path}
    appender.rolling_old.strategy.action.condition.type=IfFileName
    appender.rolling_old.strategy.action.condition.glob=${sys:es.logs.cluster_name}-*
    appender.rolling_old.strategy.action.condition.nested_condition.type=IfAccumulatedFileSize
    appender.rolling_old.strategy.action.condition.nested_condition.exceeds=2GB
    ################################################
    rootLogger.level=info
    rootLogger.appenderRef.console.ref=console
    rootLogger.appenderRef.rolling.ref=rolling
    rootLogger.appenderRef.rolling_old.ref=rolling_old
    ######## Deprecation JSON #######################
    appender.deprecation_rolling.type=RollingFile
    appender.deprecation_rolling.name=deprecation_rolling
    appender.deprecation_rolling.fileName=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_deprecation.json
    appender.deprecation_rolling.layout.type=ESJsonLayout
    appender.deprecation_rolling.layout.type_name=deprecation
    appender.deprecation_rolling.layout.esmessagefields=x-opaque-id
    appender.deprecation_rolling.filter.rate_limit.type=RateLimitingFilter
    appender.deprecation_rolling.filePattern=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_deprecation-%i.json.gz
    appender.deprecation_rolling.policies.type=Policies
    appender.deprecation_rolling.policies.size.type=SizeBasedTriggeringPolicy
    appender.deprecation_rolling.policies.size.size=1GB
    appender.deprecation_rolling.strategy.type=DefaultRolloverStrategy
    appender.deprecation_rolling.strategy.max=4
    appender.header_warning.type=HeaderWarningAppender
    appender.header_warning.name=header_warning
    #################################################
    ######## Deprecation -  old style pattern #######
    appender.deprecation_rolling_old.type=RollingFile
    appender.deprecation_rolling_old.name=deprecation_rolling_old
    appender.deprecation_rolling_old.fileName=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_deprecation.log
    appender.deprecation_rolling_old.layout.type=PatternLayout
    appender.deprecation_rolling_old.layout.pattern=[%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
    appender.deprecation_rolling_old.filePattern=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}\
      _deprecation-%i.log.gz
    appender.deprecation_rolling_old.policies.type=Policies
    appender.deprecation_rolling_old.policies.size.type=SizeBasedTriggeringPolicy
    appender.deprecation_rolling_old.policies.size.size=1GB
    appender.deprecation_rolling_old.strategy.type=DefaultRolloverStrategy
    appender.deprecation_rolling_old.strategy.max=4
    #################################################
    logger.deprecation.name=org.easysearch.deprecation
    logger.deprecation.level=deprecation
    logger.deprecation.appenderRef.deprecation_rolling.ref=deprecation_rolling
    logger.deprecation.appenderRef.deprecation_rolling_old.ref=deprecation_rolling_old
    logger.deprecation.appenderRef.header_warning.ref=header_warning
    logger.deprecation.additivity=false
    ######## Search slowlog JSON ####################
    appender.index_search_slowlog_rolling.type=RollingFile
    appender.index_search_slowlog_rolling.name=index_search_slowlog_rolling
    appender.index_search_slowlog_rolling.fileName=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs\
      .cluster_name}_index_search_slowlog.json
    appender.index_search_slowlog_rolling.layout.type=ESJsonLayout
    appender.index_search_slowlog_rolling.layout.type_name=index_search_slowlog
    appender.index_search_slowlog_rolling.layout.esmessagefields=message,took,took_millis,total_hits,types,stats,search_type,total_shards,source,id
    appender.index_search_slowlog_rolling.filePattern=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs\
      .cluster_name}_index_search_slowlog-%i.json.gz
    appender.index_search_slowlog_rolling.policies.type=Policies
    appender.index_search_slowlog_rolling.policies.size.type=SizeBasedTriggeringPolicy
    appender.index_search_slowlog_rolling.policies.size.size=1GB
    appender.index_search_slowlog_rolling.strategy.type=DefaultRolloverStrategy
    appender.index_search_slowlog_rolling.strategy.max=4
    #################################################
    ######## Search slowlog -  old style pattern ####
    appender.index_search_slowlog_rolling_old.type=RollingFile
    appender.index_search_slowlog_rolling_old.name=index_search_slowlog_rolling_old
    appender.index_search_slowlog_rolling_old.fileName=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}\
      _index_search_slowlog.log
    appender.index_search_slowlog_rolling_old.layout.type=PatternLayout
    appender.index_search_slowlog_rolling_old.layout.pattern=[%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
    appender.index_search_slowlog_rolling_old.filePattern=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}\
      _index_search_slowlog-%i.log.gz
    appender.index_search_slowlog_rolling_old.policies.type=Policies
    appender.index_search_slowlog_rolling_old.policies.size.type=SizeBasedTriggeringPolicy
    appender.index_search_slowlog_rolling_old.policies.size.size=1GB
    appender.index_search_slowlog_rolling_old.strategy.type=DefaultRolloverStrategy
    appender.index_search_slowlog_rolling_old.strategy.max=4
    #################################################
    logger.index_search_slowlog_rolling.name=index.search.slowlog
    logger.index_search_slowlog_rolling.level=trace
    logger.index_search_slowlog_rolling.appenderRef.index_search_slowlog_rolling.ref=index_search_slowlog_rolling
    logger.index_search_slowlog_rolling.appenderRef.index_search_slowlog_rolling_old.ref=index_search_slowlog_rolling_old
    logger.index_search_slowlog_rolling.additivity=false
    ######## Indexing slowlog JSON ##################
    appender.index_indexing_slowlog_rolling.type=RollingFile
    appender.index_indexing_slowlog_rolling.name=index_indexing_slowlog_rolling
    appender.index_indexing_slowlog_rolling.fileName=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}\
      _index_indexing_slowlog.json
    appender.index_indexing_slowlog_rolling.layout.type=ESJsonLayout
    appender.index_indexing_slowlog_rolling.layout.type_name=index_indexing_slowlog
    appender.index_indexing_slowlog_rolling.layout.esmessagefields=message,took,took_millis,doc_type,id,routing,source
    appender.index_indexing_slowlog_rolling.filePattern=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}\
      _index_indexing_slowlog-%i.json.gz
    appender.index_indexing_slowlog_rolling.policies.type=Policies
    appender.index_indexing_slowlog_rolling.policies.size.type=SizeBasedTriggeringPolicy
    appender.index_indexing_slowlog_rolling.policies.size.size=1GB
    appender.index_indexing_slowlog_rolling.strategy.type=DefaultRolloverStrategy
    appender.index_indexing_slowlog_rolling.strategy.max=4
    #################################################
    ######## Indexing slowlog -  old style pattern ##
    appender.index_indexing_slowlog_rolling_old.type=RollingFile
    appender.index_indexing_slowlog_rolling_old.name=index_indexing_slowlog_rolling_old
    appender.index_indexing_slowlog_rolling_old.fileName=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}\
      _index_indexing_slowlog.log
    appender.index_indexing_slowlog_rolling_old.layout.type=PatternLayout
    appender.index_indexing_slowlog_rolling_old.layout.pattern=[%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
    appender.index_indexing_slowlog_rolling_old.filePattern=${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}\
      _index_indexing_slowlog-%i.log.gz
    appender.index_indexing_slowlog_rolling_old.policies.type=Policies
    appender.index_indexing_slowlog_rolling_old.policies.size.type=SizeBasedTriggeringPolicy
    appender.index_indexing_slowlog_rolling_old.policies.size.size=1GB
    appender.index_indexing_slowlog_rolling_old.strategy.type=DefaultRolloverStrategy
    appender.index_indexing_slowlog_rolling_old.strategy.max=4
    #################################################
    logger.index_indexing_slowlog.name=index.indexing.slowlog.index
    logger.index_indexing_slowlog.level=trace
    logger.index_indexing_slowlog.appenderRef.index_indexing_slowlog_rolling.ref=index_indexing_slowlog_rolling
    logger.index_indexing_slowlog.appenderRef.index_indexing_slowlog_rolling_old.ref=index_indexing_slowlog_rolling_old
    logger.index_indexing_slowlog.additivity=false

    logger.io_netty.name = io.netty
    logger.io_netty.level = error

    logger.com_amazonaws.name = com.amazonaws
    logger.com_amazonaws.level = error

    logger.com_amazonaws_jmx_SdkMBeanRegistrySupport.name = com.amazonaws.jmx.SdkMBeanRegistrySupport
    logger.com_amazonaws_jmx_SdkMBeanRegistrySupport.level = error

    logger.com_amazonaws_metrics_AwsSdkMetrics.name = com.amazonaws.metrics.AwsSdkMetrics
    logger.com_amazonaws_metrics_AwsSdkMetrics.level = error

    logger.com_amazonaws_auth_profile_internal_BasicProfileConfigFileLoader.name = com.amazonaws.auth.profile.internal.BasicProfileConfigFileLoader
    logger.com_amazonaws_auth_profile_internal_BasicProfileConfigFileLoader.level = error

    logger.com_amazonaws_services_s3_internal_UseArnRegionResolver.name = com.amazonaws.services.s3.internal.UseArnRegionResolver
    logger.com_amazonaws_services_s3_internal_UseArnRegionResolver.level = error
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easysearch.fullname" . }}-config-script
  labels:
    {{- include "easysearch.labels" . | nindent 4 }}
data:
  unitMGR: |
    #!/bin/bash

    rm -rf /etc/confd/*
    cp -r /app/easysearch/config/* /etc/confd/
    
    cat /tmp/confd/templates/jvm.options > /etc/confd/jvm.options
    for opt in $(echo ${JAVA_OPTS}); do
      sed -i 's/'"${opt:0:4}"'1g/'"${opt}"'/' /etc/confd/jvm.options
    done
    cat /tmp/confd/templates/log4j2.options > /etc/confd/log4j2.options
    
    mkdir /etc/confd/{conf.d,templates}
    cat /tmp/confd/conf.d/confd.toml > /etc/confd/conf.d/confd.toml
    cat /tmp/confd/templates/confd.tmpl > /etc/confd/templates/confd.tmpl
    sed -ir 's/\\//g' /etc/confd/templates/confd.tmpl
    /sbin/confd -onetime -backend=env -log-level error