apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easysearch.fullname" . }}-confd-toml
  labels:
    {{- include "easysearch.labels" . | nindent 4 }}
data:
  confd.toml: |
    [template]
    src = "confd.tmpl"
    dest = "/etc/confd/easysearch.yml"
    uid = 602
    gid = 602
    mode = "0644"
    keys = ["/",]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easysearch.fullname" . }}-config-tmp
  labels:
    {{- include "easysearch.labels" . | nindent 4 }}
data:
  confd.tmpl: |-
    cluster.name: {\{getenv "CLUSTER_NAME"}\}
    node.name: {\{getenv "NODE_NAME"}\}
    #node.attr.rack: r1
    #path.data: /path/to/data
    #path.logs: /path/to/logs
    #bootstrap.memory_lock: true
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    node.roles: [{\{getenv "NODE_ROLES"}\}]
    discovery.seed_hosts: [{\{getenv "DISCOVERY_SEED_HOSTS"}\}]
    cluster.initial_master_nodes: [{\{getenv "MASTER_HOSTS"}\}]
    #gateway.recover_after_nodes: 3
    #action.destructive_requires_name: true
    #cluster.routing.allocation.disk.threshold_enabled: false
    #node.max_local_storage_nodes: 3
    #bootstrap.system_call_filter: false
    #elasticsearch.api_compatibility: true
    
    security.enabled: true
    security.audit.type: noop
    security.ssl.transport.cert_file: instance.crt
    security.ssl.transport.key_file: instance.key
    security.ssl.transport.ca_file: ca.crt
    security.ssl.transport.skip_domain_verify: true
    security.ssl.http.enabled: true
    security.ssl.http.cert_file: instance.crt
    security.ssl.http.key_file: instance.key
    security.ssl.http.ca_file: ca.crt
    security.ssl.http.enabled_ciphers:
      - "TLS_AES_128_GCM_SHA256"
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
      - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
      - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    security.ssl.http.enabled_protocols:
      - "TLSv1.2"
      - "TLSv1.3"
    security.allow_default_init_securityindex: true
    
    security.nodes_dn:
      #- 'CN=infini.cloud,OU=UNIT,O=ORG,L=NI,ST=FI,C=IN'
      - 'O=infinilabs'
    
    security.restapi.roles_enabled: [ "superuser", "security_rest_api_access" ]
    
    security.system_indices.enabled: true
    security.ssl.http.clientauth_mode: OPTIONAL
    security.system_indices.indices: [".infini-*"]
    
    #for admin dn
    ## specify admin certs to operate against system indices, basic_auth is not required
    ##  curl -k  --cert config/admin.crt --key config/admin.key   -XDELETE 'https://localhost:9200/.infini-*/'
    security.authcz.admin_dn:
      #- 'CN=admin.infini.cloud,OU=UNIT,O=ORG,L=NI,ST=FI,C=IN'
      - 'O=infinilabs'
  jvm.options: |-
    ## JVM configuration

    ################################################################
    ## IMPORTANT: JVM heap size
    ################################################################
    ##
    ## You should always set the min and max JVM heap
    ## size to the same value. For example, to set
    ## the heap to 4 GB, set:
    ##
    ## -Xms4g
    ## -Xmx4g
    ##
    ## See https://infinilabs.com/docs/latest/easysearch/getting-started/install/#JVM
    ## for more information
    ##
    ################################################################

    # Xms represents the initial size of total heap space
    # Xmx represents the maximum size of total heap space

    -Xms1g
    -Xmx1g

    ################################################################
    ## Expert settings
    ################################################################
    ##
    ## All settings below this section are considered
    ## expert settings. Don't tamper with them unless
    ## you understand what you are doing
    ##
    ################################################################

    ## GC configuration
    8-10:-XX:+UseConcMarkSweepGC
    8-10:-XX:CMSInitiatingOccupancyFraction=75
    8-10:-XX:+UseCMSInitiatingOccupancyOnly

    ## G1GC Configuration
    # NOTE: G1 GC is only supported on JDK version 10 or later
    # to use G1GC, uncomment the next two lines and update the version on the
    # following three lines to your version of the JDK
    # 10-13:-XX:-UseConcMarkSweepGC
    # 10-13:-XX:-UseCMSInitiatingOccupancyOnly
    11-:-XX:+UseG1GC
    11-:-XX:G1ReservePercent=25
    11-:-XX:InitiatingHeapOccupancyPercent=30

    ## JVM temporary directory
    -Djava.io.tmpdir=${ES_TMPDIR}

    ## JSM configuration
    17-:-Djava.security.manager=allow

    ## Locale configuration
    9-20:-Djava.locale.providers=SPI,COMPAT
    21-:-Djava.locale.providers=SPI,CLDR

    ## heap dumps

    # generate a heap dump when an allocation from the Java heap fails
    # heap dumps are created in the working directory of the JVM
    -XX:+HeapDumpOnOutOfMemoryError

    # specify an alternative path for heap dumps; ensure the directory exists and
    # has sufficient space
    -XX:HeapDumpPath=data

    # specify an alternative path for JVM fatal error logs
    -XX:ErrorFile=logs/hs_err_pid%p.log

    ## JDK 8 GC logging
    8:-XX:+PrintGCDetails
    8:-XX:+PrintGCDateStamps
    8:-XX:+PrintTenuringDistribution
    8:-XX:+PrintGCApplicationStoppedTime
    8:-Xloggc:logs/gc.log
    8:-XX:+UseGCLogFileRotation
    8:-XX:NumberOfGCLogFiles=32
    8:-XX:GCLogFileSize=64m

    # JDK 9+ GC logging
    9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easysearch.fullname" . }}-init-script
  labels:
    {{- include "easysearch.labels" . | nindent 4 }}
data:
  initialize.sh: |
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easysearch.fullname" . }}-config-script
  labels:
    {{- include "easysearch.labels" . | nindent 4 }}
data:
  unitMGR: |
    #!/bin/bash

    rm -rf /etc/confd/*
    cp -r /app/easysearch/config/* /etc/confd/
    
    cat /tmp/confd/templates/jvm.options > /etc/confd/jvm.options
    for opt in $(echo ${JAVA_OPTS})
    do
      sed -i 's/'"${opt:0:4}"'1g/'"${opt}"'/' /etc/confd/jvm.options
    done
    
    mkdir /etc/confd/{conf.d,templates}
    cat /tmp/confd/conf.d/confd.toml > /etc/confd/conf.d/confd.toml
    cat /tmp/confd/templates/confd.tmpl > /etc/confd/templates/confd.tmpl
    sed -ir 's/\\//g' /etc/confd/templates/confd.tmpl
    /sbin/confd -onetime -backend=env
