apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "easysearch.fullname" . }}
  labels:
    {{- include "easysearch.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "easysearch.selectorLabels" . | nindent 6 }}