apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "easysearch.fullname" . }}
  labels:
    {{- include "easysearch.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "easysearch.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "easysearch.fullname" . }}
  minReadySeconds: 30
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "easysearch.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 120
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "easysearch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-config
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MASTER_HOSTS
              value: '{{- toString .Values.masterHosts }}'
            - name: DISCOVERY_SEED_HOSTS
              value: '{{- toString .Values.discoverySeedHosts }}'
            - name: NODE_ROLES
              value: '{{- toString .Values.nodeRoles }}'
            - name: JAVA_OPTS
              value: '{{- toString .Values.javaOpts }}'
          command: ['/sbin/unitMGR']
          volumeMounts:
            - name: easysearch-config
              mountPath: /etc/confd
            - name: easysearch-tls
              mountPath: /app/easysearch/config/ca.crt
              subPath: ca.crt
            - name: easysearch-tls
              mountPath: /app/easysearch/config/instance.crt
              subPath: instance.crt
            - name: easysearch-tls
              mountPath: /app/easysearch/config/instance.key
              subPath: instance.key
            - name: easysearch-config-toml
              mountPath: /tmp/confd/conf.d
            - name: easysearch-config-tmpl
              mountPath: /tmp/confd/templates
            - name: easysearch-config-script
              mountPath: /sbin/unitMGR
              subPath: unitMGR
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EASYSEARCH_INITIAL_ADMIN_PASSWORD
              value: '{{- toString .Values.initAdminPassword }}'
          ports:
            - name: http
              containerPort: {{ .Values.service.http }}
              protocol: TCP
            - name: transport
              containerPort: {{ .Values.service.transport }}
              protocol: TCP
          volumeMounts:
            - name: easysearch-data
              mountPath: /app/easysearch/data
            - name: easysearch-config
              mountPath: /app/easysearch/config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: easysearch-data
          emptyDir: {}
        - name: easysearch-config
          emptyDir: {}
        - name: easysearch-config-script
          configMap:
            name: {{ include "easysearch.fullname" . }}-config-script
            defaultMode: 493
            items: 
              - key: unitMGR
                path: unitMGR
        - name: easysearch-config-toml
          configMap:
            name: {{ include "easysearch.fullname" . }}-config-toml
            defaultMode: 420
        - name: easysearch-config-tmpl
          configMap:
            name: {{ include "easysearch.fullname" . }}-config-tmpl
            defaultMode: 420
        - name: easysearch-tls
          secret:
            secretName: {{ include "easysearch.fullname" . }}-instance-secret
            defaultMode: 0600
            items:
              - key: ca.crt
                path: ca.crt
              - key: tls.crt
                path: instance.crt
              - key: tls.key
                path: instance.key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: easysearch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.dataVolumeStorage }}
    - metadata:
        name: easysearch-config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storageClassName }}
        resources:
          requests:
            storage: 1Gi