apiVersion: v1
kind: Service
metadata:
  name: {{ include "infini-console.fullname" . }}
  labels:
    {{- include "infini-console.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodeport }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "infini-console.selectorLabels" . | nindent 4 }}
